model_reasoning_effort = "high"
model_verbosity = "low"
model_reasoning_summary = "detailed"
show_raw_agent_reasoning = true
approval_policy = "on-request"
sandbox_mode = "workspace-write"
project_doc_max_bytes = 65536
project_doc_fallback_filenames = ["CLAUDE.md", "README.md"]
# network_access = true
# By default, only the cwd for the Codex session will be writable (and $TMPDIR on macOS),
# but you can specify additional writable folders in this array.
# # Replace built‑in instructions
# # `USER` must be manually replaced with the actual username
# experimental_instructions_file = "/home/USER/.codex/base_instruction.override.md"
# experimental_compact_prompt_file = "/home/USER/.codex/compact_instruction.override.md"
model = "gpt-5.2-codex"

[analytics]
enabled = false

[features]
undo = true
apply_patch_freeform = true
web_search_request = true  # allow the model to request web searches
# view_image_tool defaults to true; omit to keep defaults
steer = true
enable_request_compression = true
collab = true
collaboration_modes = true

[sandbox_workspace_write]
network_access = true
writable_roots = ["/tmp"]

[tui]
# Send desktop notifications when approvals are required or a turn completes.
# Defaults to false.
notifications = true
animations = false

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[mcp_servers.github-grep]
url = "https://mcp.grep.app"

[mcp_servers.ripgrep]
command = "npx"
args = ["-y", "mcp-ripgrep@latest"]

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.sequentialthinking-tools]
command = "npx"
args = ["-y", "mcp-sequentialthinking-tools"]

[mcp_servers.actor-critic-thinking]
command = "npx"
args = ["-y", "mcp-server-actor-critic-thinking"]

[mcp_servers.shannon-thinking]
command = "npx"
args = ["-y", "server-shannon-thinking@latest"]

[mcp_servers.time]
command = "uvx"
args = ["mcp-server-time"]

[mcp_servers.repomix]
command = "npx"
args = ["-y", "repomix", "--mcp"]
# [End] MCP Servers
